### ISSUE TITLE
Should a test be executed when skipped?

### ISSUE THREAD

**Issue by Jameskmonger** [TestAnything/Specification#23]
In the [specification](https://testanything.org/tap-specification.html), we see that the `skip` directive is used like this:

```
ok 23 # skip Insufficient flogiston pressure.
```

Does the `ok` indicate that the test was executed, passed but was skipped anyway? Or are all skipped tests not executed but reported as an `ok`?

FYI @jamesrichford

**Comment by Leont** [comment]
> Does the ok indicate that the test was executed, passed but was skipped anyway? Or are all skipped tests not executed but reported as an ok?

The latter. Skipped means the test wasn't run but success should be assumed. The opposite is a `not ok # todo`, which means it was run but the result should be pretended to have been a success.

**Comment by isaacs** [comment]
It's kind of ambiguous what the test producer means by "skip" vs "todo".

In both cases, a "not ok" status is not a failure, that's what's important from the specification's pov.

In more human terms, I've seen it used as "todo" is "I didn't run the test (or ran it, but expected it to fail) because I have work to do (either writing the test itself so it can do stuff, or writing the code for it)".  Whereas "skip" is more like "this test is normally valid, but it's not being run in this case for some reason (unsupported environment, just switched off because we're only running a subset of the suite right now, etc.)"
