### ISSUE TITLE
Platform 

### ISSUE THREAD

**Issue by Jokerboss3** [TestAnything/Specification#36]
GitHub Security · GitHub https://github.com/security

Share From App: Dev Tools(Android Developer Tools)

**Comment by mblayman** [comment]
This issue appears to be noise.

**Comment by kinow** [comment]
@Jokerboss3 these appear to be invalid issues. Please refrain from using the repository for testing or for issues without context like this. Otherwise the only alternative for maintainers of the project is to report the account to GitHub as spam and block in the TestAnything org. Thanks for cleaning up these issues @mblayman :+1:

**Comment by kinow** [comment]
Saw another post with spam and remembered about this one. I've clicked the option on this issue to report to GitHub support as spam :+1:
